name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

# --- THIS IS THE FIX ---
permissions:
  contents: write
# --------------------

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Markdown Docs from Code
        run: python generate_docs.py
        env:
          GRADIENT_ENDPOINT_URL: ${{ secrets.GRADIENT_ENDPOINT_URL }}
          GRADIENT_API_KEY: ${{ secrets.GRADIENT_API_KEY }}

      - name: Build the MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
